name: pr-validation

on:
  pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        global-json-file: global.json
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build dirs.proj
    - name: Archive antlr log for troubleshooting
      if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: antlr-log
        path: SqlScriptDom/NUL
  test: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json
      - name: Disable strong name validation
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          .\disableStrongName.ps1

      - name: Run tests Windows
        if: matrix.os == 'windows-latest'
        run: dotnet test

      - name: Run tests Linux
        if: matrix.os == 'ubuntu-latest'
        run: dotnet test /p:TargetFramework=net8.0
